### ISSUE TITLE
Console error IridiumSkyblock-3.0.4 || 3.0.5

### ISSUE THREAD

**Issue by Rialkingg** [Iridium-Development/IridiumSkyblock#222]
**Issue :**
When I use the /is menu it generates this in console

**Server version:** 1.16.5 purpurclip
**Plugin version:** 3.0.4 - 3.0.5 (The same thing happens to me with both versions)

Server log: https://pastebin.com/w7KEqn5Q

**Comment by dlsf** [comment]
Try updating to 3.0.5, if I remember correctly we already fixed this bug

**Comment by Rialkingg** [comment]
> Try updating to 3.0.5, if I remember correctly we already fixed this bug

Yesterday I tried updating from 2.6 to 3.0.4, I saw that it happened exactly the same and I updated to 3.0.5. Also crashed

**Comment by dlsf** [comment]
Can you please send us the error message using 3.0.5? It might appear to be the same, but there are probably slight differences

**Comment by Rialkingg** [comment]
Part 1 https://pastebin.com/R8inLWP8
Part 2 https://pastebin.com/XpY8eXMZ

**Comment by dlsf** [comment]
The first errors occur because of problems with Mojangs session servers, the second one is not related to IridiumSkyblock. 

Please try updating Purpur, you are 171 versions behind. If you want the skin issues to be "resolved", contact `das ist gut` (me) on our Discord server, I'll send you a beta jar.

**Comment by Rialkingg** [comment]
I updated the plugin to the latest version, I updated the purpur to the latest version of 1.16.5 and I have this error

https://pastebin.com/JQQm61KE
