### ISSUE TITLE
The server freezes completely

### ISSUE THREAD

**Issue by Serega007RU** [Iridium-Development/IridiumSkyblock#280]
Sometimes the server freezes and only helps killing the process to restart the server. Using JProfiler (this is something like Spark (spigot plugin)) I found out that the server freezes due to the IridiumSkyblock (see the screenshot). Maybe the problem is because of me (because of mods), but I would like to understand how and why this happens

Server Core: Mohist 1.12.2-162
![image](https://user-images.githubusercontent.com/64780091/125626617-0d97ce44-d732-47ae-9fe0-55501836c033.png)

**Comment by dlsf** [comment]
Please visit our support Discord and ask for a beta jar

**Comment by Serega007RU** [comment]
Why can't this be discussed here? what is beta jar? The last build of the last commit from this repository? If this is the case, I can build it myself (gradlew build), just say it. I have already contacted your guild discord, but my message was simply deleted without explaining anything.

**Comment by dlsf** [comment]
> Why can't this be discussed here? 

Because it has already been fixed. 

> what is beta jar? The last build of the last commit from this repository? If this is the case, I can build it myself (gradlew build), just say it. 

It depends on the kind of issue, sometimes it's the branch of a PR or something that has not been committed yet. In this case the master branch contains the fix. 
I was thinking about mentioning self-compiling or GitHub Actions but most users here are just confused by that so I didn't.

> I have already contacted your guild discord, but my message was simply deleted without explaining anything.

I can't really believe that. We don't delete messages as long as you don't spam or break the rules in an other way.
