### ISSUE TITLE
Islands Creating and Regening with Ocean/Land surrounding them

### ISSUE THREAD

**Issue by bloated-grap0** [Iridium-Development/IridiumSkyblock#585]
Whenever islands are created it spawns with ocean (sometimes land) around it, previously it has spawned with void around it (which is what is preferred) and as far as I can tell the ocean/land started happening around when we updated to 1.18

**Comment by dlsf** [comment]
This should only happen when the plugin is disabled while the world is loading (e.g., due to reloading, IridiumSkyblock not starting, usage of unsupported world managers with weird behaviour). 

Can you please check if this issue persists when you ensure that the plugin starts up correctly?

If it does, please send us your Minecraft & IridiumSkyblock version and your server log (aka don't delete the issue template).

**Comment by bloated-grap0** [comment]
I restarted the server a few times and the plugin started successfully running latest version 3.2.3 on 1.18.1 I do have Fast Async World Edit. 
[latest.log](https://github.com/Iridium-Development/IridiumSkyblock/files/7937651/latest.log)

**Comment by dlsf** [comment]
Did you reset the world after restarting the server? Just creating new islands obviously won't change anything. 

If it's not possible to reset the world, fly through the world and check if void generates beyond the normal world.
