### ISSUE TITLE
Selling items does not add money

### ISSUE THREAD

**Issue by CivicXFB** [Iridium-Development/IridiumSkyblock#588]
**Describe the bug**
I'm using the Vault cmi build and the spigot download version. Money is deducted on purchase but no money can be added on sale.

**To Reproduce**
1. open island shop'Normal'
2. Click to Buy 'Normal'
3. Click to sell 'Unable to sell properly'

**Expected behavior**
Gold coins are not added properly when selling items using the Island Shop No errors reported

**Server and Plugin Version**
[11:32:17 INFO]: This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)
[11:32:17 INFO]: Plugin Name: IridiumSkyblock
[11:32:17 INFO]: Plugin Version: 3.2.3

**Additional context**
 Plugins (13): Citizens, CMI, CMIEInjector*, CMILib, IridiumSkyblock, Pet, PlaceholderAPI, ProtocolLib, TAB, TrChat, TrMenu, Vault, VoidTeleportPlus

**Comment by Bayminkk** [comment]
same

**Comment by dlsf** [comment]
Update: Probably related to CMI, but I don't really know how we should proceed from here. We can't test anything related to CMI because it's a premium resource. If their developers can't solve this issue, there is nothing we can do. 

CMI's economy system will be considered as unsupported if the issue still persists.
