### ISSUE TITLE
Daily missions do not reset at midnight and more missions than listed can be completed 

### ISSUE THREAD

**Issue by Robotek019** [Iridium-Development/IridiumSkyblock#605]
**Describe the bug**
Missions do not reset at midnight server time. they also do not reset after 24 hours. after restarting the server, the problem persists and the status of the task performed 3 days ago remained the same on the test player's account. In addition, in version 3.2.5 I can perform more than the default 4 daily missions - namely, although they are not in the menu, after e.g. mining ores, I receive information in the chat about completing a mission that was not in the daily mission menu. once in a dozen openings "/ is mission DAILY" I see other missions than eg 4 minutes earlier. 

**To Reproduce**
1. Go to 'is missions daily'
2. Start the task but don't finish it 
3. Reset the game server a couple of times.
4. Wait for the next server time day. 
5. Well done, mission progress has not been reset 

**Expected behavior**
EDIT---
I found an unexpected behavior ... when it strikes midnight, completed missions reset, incomplete missions do not reset. Additionally, missions if I have more than 4 daily missions, even though they are not displayed further, I can complete them and receive a reward. The expected behavior is when they are not on the menu, they cannot be completed and incomplete missions are lost - their status is not saved.
---

**Server and Plugin Version**
Current: git-Purpur-1547 (MC: 1.18.1)*
* You are 4 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Plugin IridiumSkyblock version 3.2.5

**Screenshots**
![1](https://user-images.githubusercontent.com/47889498/153222634-beabdbb6-affc-4378-bc56-495e908507c1.png)
![2](https://user-images.githubusercontent.com/47889498/153222666-ab363341-b631-421f-b4ec-75c3258e555d.png)
![3](https://user-images.githubusercontent.com/47889498/153222678-36585f8d-4959-4a9f-8c73-b5c670852478.png)
![4](https://user-images.githubusercontent.com/47889498/153222691-32a8946e-a133-43b8-accf-d459d983ea2c.png)
![5](https://user-images.githubusercontent.com/47889498/153222696-8d324e23-e6a3-4863-bca1-ab6b6a5c8d11.png)
![6](https://user-images.githubusercontent.com/47889498/153222701-7120850b-d585-4516-b8f5-6c0bc06b5b38.png)
*Polish -> English*
1. mission one - potions 
2. mission two - mine ore
3. mission three - kill mobs
4. mission four - kill mobs 

The award I received is for a task that is not on the daily mission list. 

**Logs**
no errors... 

**Additional context**
Sorry for not finishing the correct translation, assisted by google translator

**Comment by Robotek019** [comment]
I found an unexpected behavior ... when it strikes midnight, completed missions reset, incomplete missions do not reset. Additionally, missions if I have more than 4 daily missions, even though they are not displayed further, I can complete them and receive a reward. The expected behavior is when they are not on the menu, they cannot be completed and incomplete missions are lost - their status is not saved.

And...

When I reset the entire game server again within 24 hours, the mission progress data does not reset.

**Comment by Zaoldieck** [comment]
i have the same problem here #652 

@Robotek019 about the "midnight reset" for the daily quest, I noticed that it work if u use a 1.17.1 server, so I suppose its a 1.18+ problem

**Comment by dlsf** [comment]
I'm pretty confident that this isn't related to a specific Minecraft version. We'll look into both issues.

**Comment by siskulous** [comment]
I'm commenting here because it's probably part of this issue rather than opening a duplicate issue.

I'm running into this as well, and it does not appear to be unfinished missions from previous days. Here's my /version and /is about.

[23:22:54] [Render thread/INFO]: [CHAT] Plugin Name: IridiumSkyblock
[23:22:54] [Render thread/INFO]: [CHAT] Plugin Version: 3.2.9-SNAPSHOT
[23:22:54] [Render thread/INFO]: [CHAT] Plugin Author: Peaches_MLG
[23:22:54] [Render thread/INFO]: [CHAT] Plugin Contributors: das_, SlashRemix, DoctaEnkoda
[23:22:54] [Render thread/INFO]: [CHAT] Plugin Donations: www.patreon.com/Peaches_MLG

[23:25:24] [Render thread/INFO]: [CHAT] This server is running Paper version git-Paper-"1bd678c" (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 1bd678c)\nYou are 18 version(s) behind\nDownload the new version at: https://papermc.io/downloads\nPrevious version: git-Paper-"9fd870d" (MC: 1.18.2)
