### ISSUE TITLE
checksum for Iridium Skyblock jar files

### ISSUE THREAD

**Issue by nzsmk** [Iridium-Development/IridiumSkyblock#707]
It would be good to be able to verify the download of the Iridium Skyblock jar file with some sort of  checksum. 
This could be recorded on this git and/or the spigot site.

for example paper list there sha256 in the root of there build number eg:
api.papermc.io/v2/projects/paper/versions/1.19.4/builds/504/

**Comment by dlsf** [comment]
Super late, but anyway... I kinda like the idea, but I don't see this being a thing anytime soon unless the checksum calculation gets automated, plus you could always build from source or download a recent GitHub actions build if you want to be super safe. The GitHub releases are already handled by maintainers because @PeachesMLG is super lazy, there's no way he's going to run a checksum algorithm on the jar file

**Comment by sh0inx** [comment]
if this is something we can automate, i would be willing to set it up

**Comment by sh0inx** [comment]
@nzsmk for now, you should be able to view the nexus repo, we have checksums there
https://nexus.iridiumdevelopment.net/#browse/browse:maven-public:com%2Firidium%2FIridiumSkyblock%2F4.0.4%2FIridiumSkyblock-4.0.4.jar.sha256
