### ISSUE TITLE
Compatibillity with CrossplatForms please! (Not exactly a bug)

### ISSUE THREAD

**Issue by Mateus13000** [Iridium-Development/IridiumSkyblock#709]
This plugin is so amazing, would be perfect for bedrock players to enjoin too, and CrossplatForms support would help a lot!!!

**Comment by Oybekuz** [comment]
I have Geyser plugin in my server, and bedrock players playing somehow.

The main problem was when they tried to sell items on /is shop becouse they can't right click. But some players discovered way to sell items.

I think, now bedrock players only need command for selling items (or some alternative)

**Comment by sh0inx** [comment]
i'd love to hear how you guys think we can implement support for this, because the limitation isn't within iridiumskyblock, and we aren't developing this plugin for bedrock servers; by supporting geyser servers, we would be removing functionality from java servers, which is our audience, and that's not really something that we can realistically do

**Comment by Mateus13000** [comment]
> i'd love to hear how you guys think we can implement support for this, because the limitation isn't within iridiumskyblock, and we aren't developing this plugin for bedrock servers; by supporting geyser servers, we would be removing functionality from java servers, which is our audience, and that's not really something that we can realistically do

I don't exactly have an idea, but it could be done just "porting" the java chest ui to a bedrock form ui, of course, only when the client is from geyser. I've tried to do this by myself, but I'm not the code guy 😅
