### ISSUE TITLE
convert from 3.2.9-SNAPSHOT-4 to latest

### ISSUE THREAD

**Issue by sarvarsangilov** [Iridium-Development/IridiumSkyblock#735]
Good day, I have plugin version 3.2.9-SNAPSHOT-4 on my server, and I want to update the plugin to the latest version, how can I download it while keeping all the islands.

plugin version: 3.2.9-SNAPSHOT-4
Core: git-Paper-277 (1.18.2)
and if possible, I would be happy if you could tell me how to update the kernel to 1.20.1

**Comment by sh0inx** [comment]
1) the issues page is for issues, problems, or bugs found in the latest version (master branch) of IridiumSkyblock
2) the reason we don't have a converter yet is because v4 was a complete recode, none of the data is transferrable because the code takes a different format now - converters take time, which we've been spending on fixing v4.
3) if you've downloaded paper, you should know that you can go to [paper's website](https://papermc.io/) to download the latest version, which is a build for 1.20.1 (as of this post)
4) if you need more support, join our [discord](https://discord.com/invite/6HJ73mWE7P)
