### ISSUE TITLE
Island Boosters Bug

### ISSUE THREAD

**Issue by imatspawn** [Iridium-Development/IridiumSkyblock#745]
**Describe the bug**
Able to buy boosters an unlimited amount of times

**To Reproduce**
1. /is boosters
2. Buy a booster

**Expected behavior**
A message saying "you have already purchased this booster"

**Server and Plugin Version**
Copy and paste the results of `/version` and `/is about`
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/86575849/e62a06b7-bf11-4ad5-a832-8cee218f29c0) 

**Screenshots**
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/86575849/09fcc659-4d3c-4c28-acba-bcf520310b72)
https://github.com/Iridium-Development/IridiumSkyblock/assets/86575849/2490422b-9241-4cbb-8f8f-a21f36d55413 [video, just in case]

**Logs**
If there are error messages in your console, please send them via [this](https://mclo.gs)
None

**Additional context**
That's all!

**Comment by PeachesMLG** [comment]
Not a bug, when you buy a booster when already at maximum level, it will simply add an extra hour onto the time. However, since you only display minutes and seconds onto the config, it looks like it does nothing.

I added the hour into the config by default in the latest commit, but you can also manually update your config to show this
