### ISSUE TITLE
Plugins loaded on the server but not running

### ISSUE THREAD

**Issue by flycat233** [Iridium-Development/IridiumSkyblock#833]
The plugin has been installed on the server and loaded, but there is no response when entering/is,/island, or/is create in the game or server background, and there is no error prompt in the server background
![Uploading 微信图片_20240408090402.png…]()
![Uploading 微信图片_20240408090355.png…]()

**Comment by flycat233** [comment]
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/51966564/a94c6a46-b958-4d87-9096-0057c4d37e77)
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/51966564/4bdf2a82-baa1-4263-9cd1-ef89ca6312d5)

**Comment by sh0inx** [comment]
https://mclo.gs
upload your latest.log to this website and comment the link it takes you to once you hit save

**Comment by flycat233** [comment]
https://mclo.gs/hsMR1QY

**Comment by sh0inx** [comment]
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/24255866/287e76f6-05b4-4f31-b28a-9d7cf4adea9e)

the plugin isn't working correctly because you're using a server that's running forge, and there is not a hybrid server out there that correctly implements all aspects of the bukkit api - we will not be fixing this
