### ISSUE TITLE
Players can lavacast outside the island boundries and reach the right next island and grief it.

### ISSUE THREAD

**Issue by Gargam3l** [Iridium-Development/IridiumSkyblock#851]
lava and water that the player placed can go outside from the border and cause a lavacast

**Comment by sh0inx** [comment]
This issue is both not following our issue guidelines and does not provide any useful information for us to resolve it. Please provide your latest.log file via https://mclo.gs, the size of your island, the distance between your islands, and the color of the border. Failure to do so will result in this issue being closed with no action.
