### ISSUE TITLE
SpawnerSpawnEvent is called once per entity spawn

### ISSUE THREAD

**Issue by PeachesMLG** [Iridium-Development/IridiumSkyblock#87]
SpawnerSpawnEvent is called once per entity spawn making the spawners spawn too fast

**Comment by Nubebuster** [comment]
This

**Comment by Nubebuster** [comment]
Though my solution seems very hack, it's performance efficient and it works.

**Comment by dlsf** [comment]
Starting a thread for every spawner is not efficient imo

**Comment by Nubebuster** [comment]
> Starting a thread for every spawner is not efficient imo

The code I wrote creates a runnable which is executed by an existing scheduler thread in bukkit. There is no new thread created, only a runnable. That is relatively a very inexpensive instruction. All the code is doing, put an instruction into a list that is executed the next game tick.

**Comment by Nubebuster** [comment]
Alternatively, we could check if the spawner already spawned a monster during the current tick using Bukkit.getCurrentTick(). But I can't quickly think of a way to store when the last tick was the spawner spawned something, since there are not any methods in java that I know of that have expiring data objects which would run more efficiently than this
